common: &common
  adapter: postgresql
  encoding: unicode
  username: docker
  password: docker
  template: template0
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>

development:
  <<: *common
  database: zinedistro_development

test:
  <<: *common
  database: zinedistro_test

production:
  <<: *common
  database: zinedistro_production
