common: &common
  adapter: postgresql
  host: localhost
  pool: 5
  encoding: utf8
  timeout: 5000

development:
  <<: *common
  database: distro_new_development

test:
  <<: *common
  database: distro_new_test

production:
  <<: *common
  database: distro_new_production
