common: &common
  adapter: postgresql
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *common
  database: zinedistro_development

test:
  <<: *common
  database: zinedistro_test

production:
  <<: *common
  database: zinedistro_production
